import brandImg from "../../assets/Popup/Brand.png";

const Products = [
  {
    id: 1,
    image: "./ProductImg/Apple.png",
    name: "Apple",
    category: "freshfruit",
    description: "sale",
    discount: "Sale 50%",
    price: 50,
    prices: 55.99,
    stars: 4,
    reviews: 50,
    tag: ["healthy ", "fresh ", "vegetarian "],
    Stock: false,
    featured: true,
    sku: "18,273,636",
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 2,
    image: "./ProductImg/Mango.png",
    name: "Sarjapur Mango",
    category: "freshfruit",
    description: "popular",
    discount: "Sale 50%",
    price: 100,
    prices: 100.99,
    stars: 5,
    reviews: 50,
    tag: "lowfat",
    Stock: true,
    featured: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 3,
    image: "./ProductImg/Tomato.png",
    name: "Red Tomato",
    category: "freshfruit",
    description: "latest",
    price: 200,
    Prices: 200,
    stars: 4.4,
    reviews: 50,
    tag: "vegetarian",
    Stock: true,
    featured: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 4,
    image: "./ProductImg/Cowliflower.png",
    name: "Cowliflower",
    category: "vegetables",
    description: "latest",
    price: 300,
    prices: 300.99,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    featured: true,
    brandImg: brandImg,
    tag: "healthy",
    quantity: 1,
  },
  {
    id: 5,
    image: "./ProductImg/Chilli.png",
    name: "Green Chilli",
    category: "vegetables",
    description: "sale",
    discount: "Sale 50%",
    price: 400,
    prices: 400,
    stars: 3,
    reviews: 50,
    Stock: true,
    featured: true,
    brandImg: brandImg,
    tag: "healthy",
    quantity: 1,
  },
  {
    id: 6,
    image: "./ProductImg/Eggplant.png",
    name: "Eggplant",
    category: ["healthy", "vegetarian"],
    description: "latest",
    price: 500,
    prices: 500,
    stars: 2.5,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 7,
    image: "./ProductImg/Lettuce.png",
    name: "Lettuce",
    category: "cooking",
    description: "sale",
    discount: "Sale 50%",
    price: 600,
    prices: 600,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 8,
    image: "./ProductImg/Big.png",
    name: "Big",
    category: "cooking",
    description: "popular",
    price: 700,
    prices: 700,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 18,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "popular",
    price: 800,
    prices: 800,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 9,
    image: "./ProductImg/Apple.png",
    name: "Apple",
    category: "fruit",
    description: "sale",
    discount: "Sale 50%",
    price: 900,
    prices: 900,
    stars: 4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 10,
    image: "./ProductImg/Mango.png",
    name: "Sarjapur Mango",
    category: "fruit",
    description: "popular",
    discount: "Sale 50%",
    price: 1000,
    prices: 1000,
    stars: 5,
    reviews: 50,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 11,
    image: "./ProductImg/Tomato.png",
    name: "Red Tomato",
    category: "vegetable",
    description: "loremjncjnd",
    price: 1000,
    prices: 1100,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 12,
    image: "./ProductImg/Cowliflower.png",
    name: "Cowliflower",
    category: "vegetable",
    description: "loremjncjnd",
    price: 14,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 13,
    image: "./ProductImg/Chilli.png",
    name: "Green Chilli",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: 144,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 14,
    image: "./ProductImg/Eggplant.png",
    name: "Eggplant",
    category: "vegetable",
    description: "loremjncjnd",
    price: 1450,
    stars: 2.5,
    reviews: 50,
    Stock: true,
    brandImg: brandImg,
    quantity: 1,
  },
  {
    id: 15,
    image: "./ProductImg/Lettuce.png",
    name: "Lettuce",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: 100,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    quantity: 1,
  },
  {
    id: 16,
    image: "./ProductImg/Big.png",
    name: "Big",
    category: "Vegetable",
    description: "loremjncjnd",
    price: 200,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    quantity: 1,
  },
  {
    id: 17,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: 300,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    quantity: 1,
  },
  {
    id: 18,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: 400,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    quantity: 1,
  },
  {
    id: 19,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: 350,
    stars: 4.4,
    reviews: 50,
    Stock: true,
    quantity: 1,
  },
  {
    id: 20,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: 230,
    stars: 4.4,
    reviews: 50,
    Stock: true,
  },
];

export default Products;
